/* SUPERSEDED (P1-01/02/03): the 'why', 'single', 'multi', 'startup', 'b2b' and 'features'
   records below are no longer rendered — those pages now use feature-data.js + feature-page.js
   (and features.html uses overview.js). Kept intact for reference; pages.js still renders
   pricing, testimonials, contact and blogs. See CHANGES.md. */
const pages={
why:{eyebrow:'WHY MOOREZY',title:'A smarter strategy for a stronger laundry business',intro:'More than software—an operating partner that helps you digitize, understand and scale every part of your business.',accent:'STAR',items:[['Digitize from end to end','Bring orders, customers, garments, payments and staff into one reliable system.'],['Access from anywhere','Stay connected to live operations from the store, office or your phone.'],['Acquire and retain customers','Use loyalty, referrals and campaigns to build relationships that last.'],['Turn data into action','Monitor business health with clear insights and take the right step sooner.'],['Build a valuable brand','Create consistent service, better experiences and healthier profits.'],['Scale with confidence','Open new stores and plants with a platform and support team ready for growth.']]},
single:{eyebrow:'SINGLE STORE',title:'All-in-one software for your laundry store',intro:'Increase revenue, win more customers and control expenses with a best-in-class POS and complete operating toolkit.',/* UNVERIFIED (P2-10) original: accent:'35%',accentLabel:'average revenue uplift' */accent:'One store',accentLabel:'fully under control',items:[['Powerful point of sale','Take orders quickly, price accurately and keep every customer interaction effortless.'],['Pickup & delivery','Reach new territories with customer and driver apps, route planning and live status.'],['Garment tracking','Print tags, follow every item and prevent costly mix-ups or losses.'],['Customer growth','Use referrals, loyalty points, coupons and campaigns to increase repeat business.'],['Business insights','Measure sales, expenses, services and staff performance with useful reports.'],['Payments & communication','Collect digitally and send real-time notifications throughout the order journey.']]},
multi:{eyebrow:'MULTI STORE',title:'One command center for every store and plant',intro:'Monitor, measure and manage your complete multi-store or franchise operation with effortless visibility.',/* UNVERIFIED (P2-10) original: accent:'30%',accentLabel:'potential revenue growth' */accent:'All sites',accentLabel:'one command centre',items:[['Central operations','Manage stores, plants, service territories and drivers from one dashboard.'],['Garment movement','Track every item as it flows between intake counters, processing plants and customers.'],['Shared resources','Use a common customer base, catalog, inventory and staff pool across locations.'],['Consistent processes','Give every outlet the same proven workflows, prices and service standards.'],['Consolidated reporting','Compare performance across locations and drill into the numbers that matter.'],['Brand control','Deliver a consistent customer experience while every outlet grows.']]},
startup:{eyebrow:'NEW BUSINESS',title:'Don’t just open a store. Launch it with an advantage.',intro:'Start like a pro with proven processes, modern customer experiences and technology that scales from day one.',accent:'14 days',accentLabel:'free to explore',items:[['Launch quickly','Configure services, pricing, taxes and workflows without a long implementation.'],['Professional from day one','Give customers digital receipts, updates, bookings and convenient payments.'],['Pickup & drop','Expand beyond the storefront with optimized delivery operations and laundry lockers.'],['Built-in knowledge','Use guides, videos and expert support to learn faster and avoid common mistakes.'],['Know your numbers','Track sales, costs, margins and customer behavior from the beginning.'],['A long-term IT partner','Keep adding stores, services and integrations without replacing your foundation.']]},
b2b:{eyebrow:'B2B LAUNDRY',title:'Run high-volume business accounts efficiently',intro:'Control contracts, garments, deliveries, billing and collections for hotels, hospitals, salons and corporate clients.',accent:'Faster',accentLabel:'invoicing and collections',items:[['Account-specific pricing','Maintain customer profiles, price lists, credit terms and service agreements.'],['Consolidated invoices','Generate accurate periodic invoices on time for quicker payments.'],['Delivery challans','Issue digital challans and provide real-time access through the customer app.'],['Payment reminders','Automate follow-ups for due and overdue balances.'],['Garment overview','See picked, delivered and in-process quantities for every account.'],['Scale operations','Handle more customers and volume without losing control or visibility.']]},
features:{eyebrow:'PRODUCT FEATURES',title:'Everything your laundry business needs in one place',intro:'A connected collection of practical tools designed for the counter, the road, the plant and the back office.',/* UNVERIFIED (P2-10) original: accent:'18+',accentLabel:'connected modules' */accent:'One',accentLabel:'connected platform',items:[['Point of Sale','Fast order capture, pricing, discounts, taxes and customer history.'],['Pickup & Delivery','Booking, route planning, driver apps, tracking and proof of delivery.'],['Staff Management','Roles, performance, attendance and leave management.'],['Expense Management','Capture, approve, categorize and analyze operating expenses.'],['Store & Multi-store','Central controls for locations, plants, catalogs and territories.'],['Customer Management','Profiles, preferences, credit, feedback and service history.'],['Reporting & Analytics','Live dashboards and detailed operational and financial reporting.'],['Online Payments','Payment links, cards, apps and integrated reconciliation.'],['Packages & Plans','Prepaid subscriptions that improve loyalty and cash flow.'],['Prints, Receipts & Tags','Flexible printing for invoices, garment tags and production slips.'],['Notifications & Marketing','Automated updates, campaigns, referrals and promotions.'],['Integrations & Support','Connect popular tools and get help whenever your team needs it.']]}}
const testimonials=[['The platform brought our multi-store operation under control in just one month.','Deepak G.','Pearlwash · Hyderabad'],['The support team understands laundry operations, not just software. That makes all the difference.','Anita Rao','Fresh Fold · Bengaluru'],['We opened our next outlet with confidence because every process was already standardized.','Rahul Mehta','Laundry Lab · Mumbai'],['Our customers love the pickup updates and digital payment experience.','Sara Khan','The Clean Co. · Dubai'],['Inventory and expense visibility has made our operation far more profitable.','Michael Tan','WashWorks · Singapore'],['We spend less time chasing information and more time growing the business.','Priya S.','Care Laundry · Chennai']];
function hero(p){return `<section class="page-hero"><div class="page-orb"></div><div class="container page-hero-grid"><div><span class="kicker">${p.eyebrow}</span><h1>${p.title}</h1><p>${p.intro}</p><div class="hero-actions"><a class="btn btn-primary btn-large" href="signup.html">Get started free →</a><a class="btn btn-ghost btn-large" href="contact.html">Talk to us</a></div></div><div class="metric-art"><span>${p.accent}</span><p>${p.accentLabel||'growth framework'}</p><div class="metric-chart"><i></i><i></i><i></i><i></i><i></i></div></div></div></section>`}
const featureAnchors=[['pos'],['pickup-delivery'],['staff-management','attendance'],['expense-management'],['store-management','multi-store-support'],['customer-management'],['reporting-analytics'],['online-payments'],['packages-plans'],['printing-tags'],['notifications-marketing'],['integrations-support']];
const featureIcons=['▦','⌖','♙','↘','⌂','♡','↗','$','↻','◇','✦','◎'];
function standard(p){return hero(p)+`<section class="section subpage-section"><div class="container"><div class="subpage-heading"><span class="kicker">BUILT FOR REAL OPERATIONS</span><h2>How MOOREZY helps</h2></div><div class="benefit-grid">${p.items.map((x,i)=>`<article class="benefit-card reveal">${p===pages.features?featureAnchors[i].map(id=>`<i class="anchor-target" id="${id}"></i>`).join(''):''}<div class="card-top"><span class="card-icon">${p===pages.features?featureIcons[i]:'✦'}</span><span class="card-number">${String(i+1).padStart(2,'0')}</span></div><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></div></section>${cta()}`}
function cta(){return `<section class="sub-cta"><div class="container"><h2>Ready to run a better laundry business?</h2><p>Explore MOOREZY free for 14 days. No credit card required.</p><a class="btn btn-white btn-large" href="signup.html">Start free trial →</a></div></section>`}
function pricing(){
  const plans=[
    ['Free','$0','For exploring the essentials','1 user · 1 counter',['Core laundry POS','Up to 100 customer records','Service and price catalog','Order receipts','Daily sales summary','Basic customer reports','Community help center']],
    ['Standard','$49','For independent stores','3 users · 1 store',['Everything in Free','Unlimited customers and orders','Pickup and delivery scheduling','Digital payment links','SMS and email notifications','Garment tags and printing','Staff access controls','Standard email support']],
    ['Pro','$99','For growing operations','10 users · 2 stores',['Everything in Standard','CRM and customer segments','Campaigns, loyalty and referrals','Inventory and consumption tracking','Expenses and approvals','Prepaid packages and subscriptions','Advanced operational reports','Priority support']],
    ['Growth','$199','For multi-store teams','Unlimited users · 10 stores',['Everything in Pro','Central multi-store controls','Store-to-plant garment flow','Driver and territory management','Shared catalog and inventory','Consolidated financial analytics','Staff attendance and performance','Onboarding assistance']],
    ['Enterprise','Talk to us','For complex networks','Custom users and locations',['Everything in Growth','Custom workflows and permissions','Franchise and aggregator controls','Tailored integrations and APIs','Data migration assistance','Dedicated success manager','Priority incident response','Custom training and service levels']]
  ];
  /* P2-05 — plan comparison. Every cell is derived from the plan descriptions above it,
     so this restructures existing claims rather than inventing new limits. Cells marked
     'ask' are genuinely unspecified in the current plan copy and need confirming
     (see CLAIMS-REVIEW.md section 5) rather than being guessed at. */
  const Y='<td class="yes">✓</td>', N='<td class="no">—</td>', A='<td class="ask">Ask us</td>';
  const compareRows=[
    ['group','Limits'],
    ['Users','<td>1</td><td>3</td><td>10</td><td>Unlimited</td><td>Custom</td>'],
    ['Stores','<td>1 counter</td><td>1</td><td>2</td><td>10</td><td>Custom</td>'],
    ['Customer records','<td>Up to 100</td><td>Unlimited</td><td>Unlimited</td><td>Unlimited</td><td>Unlimited</td>'],
    ['group','At the counter'],
    ['Point of sale',Y+Y+Y+Y+Y],
    ['Service &amp; price catalogue',Y+Y+Y+Y+Y],
    ['Order receipts',Y+Y+Y+Y+Y],
    ['Garment tags &amp; printing',N+Y+Y+Y+Y],
    ['Staff access controls',N+Y+Y+Y+Y],
    ['group','Delivery &amp; apps'],
    ['Pickup &amp; delivery scheduling',N+Y+Y+Y+Y],
    ['Driver &amp; territory management',N+N+N+Y+Y],
    ['Customer app &amp; online booking',A+A+A+A+A],
    ['group','Customers &amp; growth'],
    ['CRM &amp; customer segments',N+N+Y+Y+Y],
    ['Campaigns, loyalty &amp; referrals',N+N+Y+Y+Y],
    ['SMS &amp; email notifications',N+Y+Y+Y+Y],
    ['Prepaid packages &amp; subscriptions',N+N+Y+Y+Y],
    ['group','Operations'],
    ['Inventory &amp; consumption tracking',N+N+Y+Y+Y],
    ['Expenses &amp; approvals',N+N+Y+Y+Y],
    ['Staff attendance &amp; performance',N+N+N+Y+Y],
    ['Central multi-store controls',N+N+N+Y+Y],
    ['Store-to-plant garment flow',N+N+N+Y+Y],
    ['group','Money &amp; insight'],
    ['Digital payment links',N+Y+Y+Y+Y],
    ['Daily sales summary',Y+Y+Y+Y+Y],
    ['Advanced operational reports',N+N+Y+Y+Y],
    ['Consolidated financial analytics',N+N+N+Y+Y],
    ['group','Platform &amp; service'],
    ['Integrations',A+A+A+A+A],
    ['Data migration assistance',N+N+N+N+Y],
    ['Onboarding assistance',N+N+N+Y+Y],
    ['Support','<td>Community</td><td>Email</td><td>Priority</td><td>Priority</td><td>Dedicated</td>']
  ];
  const compare=`<section class="prod-section tint"><div class="container">
    <div class="prod-head centered"><span class="kicker">COMPARE PLANS</span><h2>What is included, side by side</h2><p>Scroll sideways to see every plan. This table mirrors the plan descriptions above.</p></div>
    <div class="plan-table-wrap"><table class="plan-table">
      <thead><tr><th scope="col">Feature</th>${plans.map(p=>`<th scope="col">${p[0]}</th>`).join('')}</tr></thead>
      <tbody>${compareRows.map(r=>r[0]==='group'
        ? `<tr class="group"><th scope="colgroup" colspan="6">${r[1]}</th></tr>`
        : `<tr><th scope="row">${r[0]}</th>${r[1]}</tr>`).join('')}</tbody>
    </table></div>
    <p class="plan-note">Prices are shown per month for comparison. Taxes and final commercial terms vary by region. Rows marked <b>Ask us</b> depend on your configuration or region and are confirmed before you commit — we would rather tell you accurately than list something that turns out not to apply to you.</p>
  </div></section>`;

  return `<section class="page-hero compact"><div class="container center"><span class="kicker">SIMPLE & TRANSPARENT</span><h1>Pricing that grows with you</h1><p>Start small, upgrade when you’re ready, and never pay for complexity you don’t need.</p><div class="pricing-note"><span>✓ 14-day free trial</span><span>✓ No credit card</span><span>✓ Upgrade anytime</span></div></div></section><section class="section pricing-section"><div class="container pricing-grid">${plans.map((p,i)=>`<article class="price-card ${i===2?'popular':''}">${i===2?'<b class="popular-label">MOST POPULAR</b>':''}<h2>${p[0]}</h2><div class="price">${p[1]}</div><p>${p[2]}</p><small class="plan-scope">${p[3]}</small><a class="btn ${i===2?'btn-primary':'btn-ghost'}" href="${i===4?'contact.html':'signup.html'}">${i===4?'Contact sales':'Start free'}</a><div class="included-label">WHAT'S INCLUDED</div><ul>${p[4].map(x=>`<li><span>✓</span>${x}</li>`).join('')}</ul></article>`).join('')}</div><div class="pricing-footnote">Prices are shown per month for comparison. Taxes and final commercial terms may vary by region.</div></section>${compare}<section class="pricing-faq"><div class="container"><div class="section-heading centered"><span class="kicker">PRICING FAQ</span><h2>Questions before you start?</h2></div><div class="faq-grid"><article><h3>Can I change plans later?</h3><p>Yes. Move up as your team and store network grow. Final billing adjustments will be defined when subscriptions are connected.</p></article><article><h3>Is setup included?</h3><p>Self-guided setup is available to every plan. Assisted onboarding is included with Growth and Enterprise.</p></article><article><h3>Can I import existing data?</h3><p>Customer, service and product imports are supported. Complex migration is available for Enterprise customers.</p></article><article><h3>Where can I read more questions?</h3><p>The full list — setup, migration, printers, devices, multi-store, drivers, online booking, payments, training and support — is on the <a href="faq.html">FAQ page</a>.</p></article><article><h3>Are payments active now?</h3><p>Not yet. This is the frontend pricing experience; secure subscription billing will be connected with the backend.</p></article></div></div></section>${cta()}`}
/* Outcome labels are descriptive only. Replace with verified, customer-approved results
   before launch — see CLAIMS-REVIEW.md (P2-01, P2-02, P2-10).
   UNVERIFIED originals, kept for reference:
   ['94% fewer garment losses','3 outlets standardized','Faster new-store launch',
    'Higher repeat bookings','8.2% lower operating cost','More time focused on growth'] */
const testimonialResults=['Fewer garment losses','Outlets standardised','Faster new-store launch','More repeat bookings','Tighter cost control','More time to grow'];
function testimonialPage(){return `<section class="page-hero compact"><div class="container center"><span class="kicker">CUSTOMER STORIES</span><h1>Loved by laundry teams worldwide</h1><p>We work as a technology partner, earning trust with responsive support and practical solutions.</p></div></section><section class="section testimonial-page-section"><div class="container testimonial-cards">${testimonials.map((t,i)=>`<article class="review reveal"><div class="review-head"><span class="review-avatar">${t[1].split(/\s+/).map(x=>x[0]).join('').slice(0,2)}</span><span class="review-meta"><b>${t[1]}</b><small>${t[2]}</small></span><span class="review-rating">★★★★★</span></div><blockquote>“${t[0]}”</blockquote><div class="review-result">${testimonialResults[i]}</div></article>`).join('')}</div></section>${cta()}`}
function contact(){return `<section class="page-hero compact"><div class="container center"><span class="kicker">CONTACT US</span><h1>Let’s talk about your business</h1><p>Tell us what you’re building and our laundry technology specialists will help you find the right setup.</p></div></section><section class="section"><div class="container contact-grid"><div><span class="kicker">WE'RE HERE TO HELP</span><h2>Talk to a real person</h2><p>Questions about setup, pricing, migration or a custom operation? Reach out and our team will respond.</p><div class="contact-detail"><b>Email</b><a href="mailto:hello@moorezy.com">hello@moorezy.com</a></div><div class="contact-detail"><b>Product access</b><a href="login.html">Sign in to MOOREZY</a></div></div><form class="contact-form" action="mailto:hello@moorezy.com" method="post" enctype="text/plain"><label>Name<input name="name" required></label><label>Business email<input type="email" name="email" required></label><label>Phone<input type="tel" name="phone"></label><label>Business type<select name="business"><option>Single store</option><option>Multi store</option><option>New business</option><option>B2B / Plant</option></select></label><label class="full">How can we help?<textarea name="message" rows="5" required></textarea></label><button class="btn btn-primary btn-large" type="submit">Send enquiry →</button></form></div></section>
<section class="prod-section tint"><div class="container"><div class="prod-head"><span class="kicker">SUPPORT</span><h2>How we help after you go live</h2><p>Getting the software is the easy part. Getting your team using it properly is what we actually help with.</p></div><div class="cap-grid">
<article class="cap"><span class="cap-mark">✦</span><b>Guided onboarding</b><p>We configure services, pricing, taxes and workflows with you rather than handing over a blank system.</p></article>
<article class="cap"><span class="cap-mark">✦</span><b>Data import</b><p>Existing customers, services and price lists can be brought across. Larger migrations are handled case by case.</p></article>
<article class="cap"><span class="cap-mark">✦</span><b>Team training</b><p>Counter staff, drivers and managers are walked through the parts of the system they actually use.</p></article>
<article class="cap"><span class="cap-mark">✦</span><b>Ongoing support</b><p>Help once you are running. Response times and channels depend on your plan — ask us what applies to you.</p></article>
</div></div></section>
<section class="prod-section"><div class="container"><div class="prod-head"><span class="kicker">COMMON QUESTIONS</span><h2>Before you get in touch</h2></div><div class="faq-list">
<details class="faq-item"><summary>How long does setup take?</summary><p>It depends on how many stores, services and existing records you have. A single store with a straightforward catalogue is fast; a multi-store network with a plant takes longer. Tell us your setup and we will give you a realistic estimate.</p></details>
<details class="faq-item"><summary>Can we try it before committing?</summary><p>Yes — there is a 14-day free trial and no credit card is required to start.</p></details>
<details class="faq-item"><summary>Can you migrate our existing data?</summary><p>Customer, service and price imports are supported. Send us a sample of what you hold today and we will confirm what can be brought across.</p></details>
<details class="faq-item"><summary>Do you support our printers and scanners?</summary><p>MOOREZY is designed to work with standard label and receipt printers and barcode scanners. Send us your models and we will confirm compatibility before you buy anything.</p></details>
<details class="faq-item"><summary>We run a plant as well as stores. Is that supported?</summary><p>Yes. Garments move between stores and the plant as tracked lots, and return to the store they came from. See <a href="factory-plant.html">Factory &amp; Plant</a>.</p></details>
</div></div></section>`}
function blogs(){let posts=[['Inventory','Laundry Inventory Management Best Practices for Owners'],['Technology','How a Laundry Online Booking System Is Changing the Industry'],['Operations','Staff Scheduling Software: Solving Labor Shortages'],['Automation','Automating Garment Tracking with Barcode and RFID'],['Growth','Customer Loyalty Programs Built Into Modern Laundry Software'],['Delivery','How a Laundry POS System Is Transforming Pickup and Delivery']];return `<section class="page-hero compact"><div class="container center"><span class="kicker">LAUNDRY & DRY CLEANING</span><h1>Ideas for a cleaner, smarter business</h1><p>Practical guides on operations, technology, customer experience and growth.</p></div></section><section class="section"><div class="container blog-grid">${posts.map((p,i)=>`<article class="blog-card reveal"><div class="blog-art art-${i+1}"><span>${p[0]}</span></div><div><span class="kicker">${p[0]}</span><h2>${p[1]}</h2><p>Practical strategies and modern tools to help laundry owners operate efficiently and grow sustainably.</p><a href="contact.html">Read article →</a></div></article>`).join('')}</div></section>${cta()}`}
const key=document.body.dataset.page;const mount=document.querySelector('#page-content');if(mount){if(pages[key])mount.innerHTML=standard(pages[key]);else if(key==='pricing')mount.innerHTML=pricing();else if(key==='testimonials')mount.innerHTML=testimonialPage();else if(key==='contact')mount.innerHTML=contact();else if(key==='blogs')mount.innerHTML=blogs()}
if(location.hash){requestAnimationFrame(()=>document.querySelector(location.hash)?.scrollIntoView({behavior:'smooth',block:'start'}))}
/* Nav, dropdowns, reveal and back-to-top all live in components.js. */
window.initReveal?.(mount||document);
